name: dependencies
on: push
jobs:
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: stepA
        run: echo "world"
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: stepB
        run: echo "Hello"
